services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
