services:
  nginx:
    image: nginx:1.27.5
    container_name: nginx_proxy
    ports:
      - "4567:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
